[package]
name = "cuts-cli"
version = "0.1.1"
edition = "2024"
description = "cli for cuts"
license = "MIT"
repository = "https://github.com/boyangsic/cuts"


[dependencies]
walkdir = "2.5.0"
cuts-core = { path = "../core", version = "0.1.0" }
rand = "0.10.0"
rpassword = "7.3.1"
zeroize = "1.8.2"

[[bin]]
name = "cuts"
path = "src/main.rs"