[package]
name = "cuts-core"
version = "0.1.0"
edition = "2024"
description = "core library for cuts"
license = "MIT"
repository = "https://github.com/boyangsic/cuts"

[dependencies]
bitflags = "2.11.0"
blake3 = "1.8.3"
byteorder = "1.5.0"
chacha20-poly1305 = "0.1.2"
hkdf = "0.12.4"
lz4 = "1.28.1"
rand = "0.10.0"
sha2 = "0.10.9"
